name: Docker

on: push

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bout-base
      USER: oi4ai
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "mpich full"
            mpi: "mpich"
            type: "full"

          - name: "mpich mini"
            mpi: "mpich"
            type: "mini"
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ env.USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            MPI=${{ matrix.config.mpi }}
            TYPE=${{ matrix.config.type }}
          tags: |
            ${{ env.USER }}/${{ env.IMAGE_NAME }}:openmp-${{ matrix.config.mpi }}-${{ matrix.config.type }}

