name: Docker

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run on the 7th of each month at 13:37 to ensure the image stays up-to-date
    - cron:  '37 13 7 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: true
      matrix:
        mpi: [mpich, openmpi]
        type: [full, mini]
        config:
          - name: "With openmp"
            openmp: 1
            prefix: "openmp-"
          - name: "Without openmp"
            openmp: 0
            prefix: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            prefix=${{ matrix.mpi }}-${{ matrix.config.prefix }}${{ matrix.type }}-

      - name: Build and push Docker image
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497
        with:
          build-args: |
            MPI=${{ matrix.mpi }}
            TYPE=${{ matrix.type }}
            OPENMP=${{ matrix.config.openmp }}
            PETSC_VERSION=3.22.1
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
