name: Docker

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run on the 7th of each month at 13:37 to ensure the image stays up-to-date
    - cron:  '37 13 7 * *'

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bout-base
      USER: oi4ai
    strategy:
      fail-fast: true
      matrix:
        mpi: [mpich, openmpi]
        type: [full, mini]
        config:
          - name: "With openmp"
            openmp: 1
            prefix: "openmp-"
          - name: "Without openmp"
            openmp: 0
            prefix: ""
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ env.USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            MPI=${{ matrix.mpi }}
            TYPE=${{ matrix.type }}
            OPENMP=${{ matrix.config.openmp }}
          tags: |
            ${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ matrix.config.prefix }}${{ matrix.mpi }}-${{ matrix.type }}

