name: KeepAlive
on:
  schedule:
    - cron: "0 0 5 * *"

jobs:
  keepalive:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Keep alive commit"
          commit_options: '--allow-empty'
