name: KeepAlive
on:
  schedule:
    - cron: "0 0 */5 * *"

jobs:
  keepalive:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
